# Generated by Django 3.1.4 on 2020-12-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category_choices', models.CharField(choices=[('11', 'Vegetation'), ('12', 'Trees'), ('13', 'Nature'), ('14', 'Abstract'), ('15', 'IT & Computers'), ('16', 'Animals'), ('17', 'Illustrations'), ('18', 'Arts'), ('19', 'Business'), ('20', 'Industries'), ('21', 'Objects'), ('22', 'Technology'), ('23', 'People'), ('24', 'Travel')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=20)),
                ('image_description', models.CharField(max_length=30)),
                ('image', models.ImageField(blank='True', null='True', upload_to='photos/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display.location')),
            ],
            options={
                'ordering': ['image_name'],
            },
        ),
    ]
